### ISSUE TITLE
Add Repo Description

### ISSUE THREAD

**Issue by chamathpali** [99xt/react-boilerplate#12]

**Comment by chamathpali** [comment]
Added: Unopinionated boilerplate for react, react-flux or react-redux.
Change and close the issue :)

**Comment by rajikaimal** [comment]
@charithsoori Safe to close this :smile_cat:

**Comment by charithsoori** [comment]
Ahh, nice. We must do some work in related repositories and get some community traction. Let's create few issues to follow up and modernise this.
